add sitemaps
flexbox/artaufeminin pull request #78
Opened 2021-12-09 13:36 UTC by MatthysDucrocq

2021-12-09 16:04 UTC, flexbox requested changes

2021-12-09 16:04 UTC, flexbox commented on src/components/episodeItem.tsx
> +          <Text as="h3Link">{episode.title} | Podcast ART au feminin</Text>
This needs to be in the 
```html
<head>
<title>S02E01 : Camille Claudel - Artiste - Muse de Rodin - Trente | Podcast ART au feminine</title>
</head>

2021-12-09 16:14 UTC, MatthysDucrocq commented on src/components/episodeItem.tsx
> +          <Text as="h3Link">{episode.title} | Podcast ART au feminin</Text>
Fix

2021-12-10 10:25 UTC, flexbox approved these changes

2021-12-10 10:26 UTC, merged